# to mirror file name
name: tests-tickets

# determines when we run this workflow: whenever we create, reopen or update pull request
on:
  pull_request:
    paths:
      - 'tickets/**' # if pull_request AND any file in tickets directory has changed, then run below job

# jobs section will define workflow: a number of things to do
# we want to start up a container on a VM, run on ubuntu os, and first step we want to do is use all the code out of our project
# we'll then set up a series of commands to run inside project -- for now, run all tests in tickets service
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
